<?php

namespace Database\Seeders;

use App\Models\Delitos;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DelitoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $datos = [
            ["clave"=> "1","nombre" => "ABANDONO, OMISION DE CUIDADOS E INCUMPLIMIENTO DE OBLIGACIONES ALIMENTARIAS"],
            ["clave"=> "2","nombre" => "ABORTO (RESPONSABILIDAD PROFESIONAL)"],
            ["clave"=> "3","nombre" => "AMENAZAS"],
            ["clave"=> "4","nombre" => "AGRESIONES"],
            ["clave"=> "5","nombre" => "EJECUCION EXTRAJUDICIAL"],
            ["clave"=> "6","nombre" => "FEMINICIDIO"],
            ["clave"=> "7","nombre" => "HOMICIDIO"],
            ["clave"=> "8","nombre" => "LESIONES"],
            ["clave"=> "9","nombre" => "TORTURA"],
            ["clave"=> "10","nombre" => "TRATOS O PENAS CRUELES, INHUMANOS O DEGRADANTES"],
            ["clave"=> "11","nombre" => "VIOLENCIA FAMILIAR"],
            ["clave"=> "12","nombre" => "FEMINICIDIO EN GRADO DE TENTATIVA"],
            ["clave"=> "13","nombre" => "HOMICIDIO EN GRADO DE TENTATIVA"],
            ["clave"=> "14","nombre" => "OTROS DELITOS QUE ATENTAN CONTRA LA VIDA Y LA INTEGRIDAD CORPORAL"],
            ["clave"=> "15","nombre" => "DESAPARICION DE PERSONAS (SIN ESPECIFICAR FORZADA O POR PARTICULARES)"],
            ["clave"=> "16","nombre" => "DESAPARICION FORZADA"],
            ["clave"=> "17","nombre" => "DESAPARICION POR PARTICULARES"],
            ["clave"=> "18","nombre" => "DETENCION ARBITRARIA O RETENCION ILEGAL"],
            ["clave"=> "19","nombre" => "PRIVACION ILEGAL DE LA LIBERTAD"],
            ["clave"=> "20","nombre" => "RAPTO"],
            ["clave"=> "21","nombre" => "RETENCION O SUSTRACCION DE MENORES E INCAPACES"],
            ["clave"=> "22","nombre" => "SECUESTRO"],
            ["clave"=> "23","nombre" => "TRAFICO DE MENORES"],
            ["clave"=> "24","nombre" => "SECUESTRO EN GRADO DE TENTATIVA"],
            ["clave"=> "25","nombre" => "OTROS DELITOS QUE ATENTAN CONTRA LA LIBERTAD PERSONAL"],
            ["clave"=> "26","nombre" => "ABUSO SEXUAL"],
            ["clave"=> "27","nombre" => "ACOSO SEXUAL"],
            ["clave"=> "28","nombre" => "CORRUPCION DE MENORES E INCAPACES"],
            ["clave"=> "29","nombre" => "DISCRIMINACION"],
            ["clave"=> "30","nombre" => "ESTUPRO"],
            ["clave"=> "31","nombre" => "HOSTIGAMIENTO SEXUAL"],
            ["clave"=> "32","nombre" => "INCESTO"],
            ["clave"=> "33","nombre" => "LENOCINIO"],
            ["clave"=> "34","nombre" => "PEDERASTIA"],
            ["clave"=> "35","nombre" => "PORNOGRAFIA INFANTIL"],
            ["clave"=> "36","nombre" => "PROSTITUCION DE MENORES E INCAPACES"],
            ["clave"=> "37","nombre" => "TRATA DE PERSONAS"],
            ["clave"=> "38","nombre" => "TURISMO SEXUAL"],
            ["clave"=> "39","nombre" => "VIOLACION"],
            ["clave"=> "40","nombre" => "VIOLENCIA DE GENERO"],
            ["clave"=> "41","nombre" => "OTROS DELITOS QUE ATENTAN CONTRA EL LIBRE DESARROLLO DE LA PERSONALIDAD Y LA SEGURIDAD SEXUAL"],
            ["clave"=> "42","nombre" => "ABIGEATO"],
            ["clave"=> "43","nombre" => "ABUSO DE CONFIANZA"],
            ["clave"=> "44","nombre" => "ALLANAMIENTO"],
            ["clave"=> "45","nombre" => "DAÑO A LA PROPIEDAD"],
            ["clave"=> "46","nombre" => "DESPOJO"],
            ["clave"=> "47","nombre" => "EXTORSION"],
            ["clave"=> "48","nombre" => "FRAUDE"],
            ["clave"=> "49","nombre" => "ROBO (SIMPLE O CON VIOLENCIA)"],
            ["clave"=> "50","nombre" => "ROBO A CASA HABITACION O INMUEBLE"],
            ["clave"=> "51","nombre" => "ROBO DE VEHICULO"],
            ["clave"=> "52","nombre" => "ROBO A TRANSPORTISTA DE CARGA"],
            ["clave"=> "53","nombre" => "ROBO A TRANSPORTE DE PASAJEROS"],
            ["clave"=> "54","nombre" => "OTROS DELITOS QUE ATENTAN CONTRA EL PATRIMONIO"],
            ["clave"=> "55","nombre" => "ASOCIACION DELICTUOSA"],
            ["clave"=> "56","nombre" => "DELINCUENCIA ORGANIZADA"],
            ["clave"=> "57","nombre" => "EN MATERIA DE ARMAS, EXPLOSIVOS Y OTROS MATERIALES DESTRUCTIVOS"],
            ["clave"=> "58","nombre" => "EN MATERIA DE HIDROCARBUROS Y SUS DERIVADOS"],
            ["clave"=> "59","nombre" => "EVASION DE PRESOS"],
            ["clave"=> "60","nombre" => "NARCOMENUDEO (CONTRA LA SALUD RELACIONADOS CON NARCOTICOS EN EL AMBITO LOCAL)"],
            ["clave"=> "61","nombre" => "NARCOTRAFICO (CONTRA LA SALUD RELACIONADOS CON NARCOTICOS EN EL AMBITO FEDERAL)"],
            ["clave"=> "62","nombre" => "TERRORISMO"],
            ["clave"=> "63","nombre" => "TRAFICO DE PERSONAS"],
            ["clave"=> "64","nombre" => "OTROS DELITOS EN MATERIA DE MIGRACION"],
            ["clave"=> "65","nombre" => "OTROS DELITOS CONTRA LA SEGURIDAD PUBLICA Y LA SEGURIDAD DEL ESTADO"],
            ["clave"=> "66","nombre" => "ABUSO DE AUTORIDAD"],
            ["clave"=> "67","nombre" => "COHECHO"],
            ["clave"=> "68","nombre" => "CONTRA LA ADMINISTRACION DE JUSTICIA"],
            ["clave"=> "69","nombre" => "EJERCICIO ABUSIVO DE FUNCIONES"],
            ["clave"=> "70","nombre" => "EJERCICIO INDEBIDO DEL SERVICIO PUBLICO"],
            ["clave"=> "71","nombre" => "ELECTORALES Y EN MATERIA DE VIOLENCIA POLITICA"],
            ["clave"=> "72","nombre" => "EN MATERIA DE AMPARO"],
            ["clave"=> "73","nombre" => "EN MATERIA FISCAL"],
            ["clave"=> "74","nombre" => "ENRIQUECIMIENTO ILICITO"],
            ["clave"=> "75","nombre" => "FALSEDAD EN DECLARACIONES"],
            ["clave"=> "76","nombre" => "FALSIFICACION Y ALTERACION DE DOCUMENTOS"],
            ["clave"=> "77","nombre" => "PECULADO"],
            ["clave"=> "78","nombre" => "TRAFICO DE INFLUENCIAS"],
            ["clave"=> "79","nombre" => "OPERACIONES CON RECURSOS DE PROCEDENCIA ILICITA"],
            ["clave"=> "80","nombre" => "OTROS DELITOS POR HECHOS DE CORRUPCION"],
            ["clave"=> "81","nombre" => "OTROS DELITOS CONTRA LA ADMINISTRACION DEL ESTADO"],
            ["clave"=> "82","nombre" => "CONTRA EL ACCESO A LA INFORMACION Y EL DERECHO A LA VERDAD"],
            ["clave"=> "83","nombre" => "CONTRA EL MEDIOAMBIENTE, LA BIODIVERSIDAD Y LA GESTION AMBIENTAL"],
            ["clave"=> "84","nombre" => "CONTRA LA LIBERTAD DE EXPRESION Y DE REUNION"],
            ["clave"=> "85","nombre" => "CONTRA LA SEGURIDAD DE LOS DATOS Y/O SISTEMAS O EQUIPOS INFORMATICOS"],
            ["clave"=> "86","nombre" => "EN MATERIA DE DERECHOS DE AUTOR"],
            ["clave"=> "87","nombre" => "EN MATERIA DE INSTITUCIONES DE CREDITO, INVERSION, FIANZAS Y SEGUROS"],
            ["clave"=> "88","nombre" => "EN MATERIA DE PROPIEDAD INDUSTRIAL"],
            ["clave"=> "89","nombre" => "EN MATERIA DE COMUNICACIONES Y CORRESPONDENCIA"],
            ["clave"=> "90","nombre" => "ENCUBRIMIENTO"],
            ["clave"=> "91","nombre" => "NEGLIGENCIA MEDICA"],
            ["clave"=> "92","nombre" => "SUPLANTACION Y USURPACION DE IDENTIDAD"],
            ["clave"=> "93","nombre" => "TRAFICO DE ORGANOS"],
            ["clave"=> "94","nombre" => "DESPLAZAMIENTO FORZADO INTERNO"],
            ["clave"=> "95","nombre" => "OTROS DELITOS CONTRA LA SALUD"],
            ["clave"=> "96","nombre" => "OTROS DELITOS POR RESPONSABILIDAD PROFESIONAL"],
            ["clave"=> "97","nombre" => "OTROS DELITOS"],
            ["clave"=> "98","nombre" => "ERROR DE CAPTURA O DE LLENADO DEL FUD"],
            ["clave"=> "99","nombre" => "NO APLICA"],
            ["clave"=> "100","nombre" => "TIPO DE DELITO NO ESPECIFICADO"],
            ["clave"=> "101","nombre" => "VIOLENCIA DIGITAL"],
            ["clave"=> "102","nombre" => "VIOLACION A LA INTIMIDAD SEXUAL"],
            ["clave"=> "103","nombre" => "PRIVACION DE LA LIBERTAD EN GRADO DE TENTATIVA"],
            ["clave"=> "104","nombre" => "EXHIBICIONISMO CORPORAL"],
            ["clave"=> "105","nombre" => "PORTACION DE EQUIPOS QUE BLOQUEEN, CANCELEN O ANULEN LAS SEÑALES DE TELEFONIA CELULAR, DE RADIOCOMUNICACION O DE TRANSMISION DE DATOS O IMAGEN"],
            ["clave"=> "106","nombre" => "OTRO"],

        ];

        foreach($datos as $dato)
            Delitos::create($dato);
    }
}
