<?php

namespace Database\Seeders;

use App\Models\Pais;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $datos = [
            ["clave" => "1","nombre" => "AFGANISTAN"],
            ["clave" => "2","nombre" => "ALBANIA"],
            ["clave" => "3","nombre" => "ALEMANIA"],
            ["clave" => "4","nombre" => "ANDORRA"],
            ["clave" => "5","nombre" => "ANGOLA"],
            ["clave" => "6","nombre" => "ANGUILA"],
            ["clave" => "7","nombre" => "ANTARTICA"],
            ["clave" => "8","nombre" => "ANTIGUA Y BARBUDA"],
            ["clave" => "9","nombre" => "ANTILLAS NEERLANDESAS"],
            ["clave" => "10","nombre" => "ARABIA SAUDITA"],
            ["clave" => "11","nombre" => "ARGELIA"],
            ["clave" => "12","nombre" => "ARGENTINA"],
            ["clave" => "13","nombre" => "ARMENIA"],
            ["clave" => "14","nombre" => "ARUBA"],
            ["clave" => "15","nombre" => "AUSTRALIA"],
            ["clave" => "16","nombre" => "AUSTRIA"],
            ["clave" => "17","nombre" => "AZERBAIYAN"],
            ["clave" => "18","nombre" => "BAHAMAS"],
            ["clave" => "19","nombre" => "BAHREIN"],
            ["clave" => "20","nombre" => "BANGLADESH"],
            ["clave" => "21","nombre" => "BARBADOS"],
            ["clave" => "22","nombre" => "BELARUS"],
            ["clave" => "23","nombre" => "BELGICA"],
            ["clave" => "24","nombre" => "BELICE"],
            ["clave" => "25","nombre" => "BENIN"],
            ["clave" => "26","nombre" => "BERMUDA"],
            ["clave" => "27","nombre" => "BHUTAN"],
            ["clave" => "28","nombre" => "BOLIVIA"],
            ["clave" => "29","nombre" => "BOSNIA Y HERZEGOVINA"],
            ["clave" => "30","nombre" => "BOTSWANA"],
            ["clave" => "31","nombre" => "BRASIL"],
            ["clave" => "32","nombre" => "BRUNEI DARUSSALAM"],
            ["clave" => "33","nombre" => "BULGARIA"],
            ["clave" => "34","nombre" => "BURKINA FASO"],
            ["clave" => "35","nombre" => "BURUNDI"],
            ["clave" => "36","nombre" => "CABO VERDE"],
            ["clave" => "37","nombre" => "CAMBOYA"],
            ["clave" => "38","nombre" => "CAMERUN"],
            ["clave" => "39","nombre" => "CANADA"],
            ["clave" => "40","nombre" => "CHAD"],
            ["clave" => "41","nombre" => "CHILE"],
            ["clave" => "42","nombre" => "CHINA"],
            ["clave" => "43","nombre" => "CHIPRE"],
            ["clave" => "44","nombre" => "COLOMBIA"],
            ["clave" => "45","nombre" => "COMORAS"],
            ["clave" => "46","nombre" => "CONGO"],
            ["clave" => "47","nombre" => "COSTA DE MARFIL"],
            ["clave" => "48","nombre" => "COSTA RICA"],
            ["clave" => "49","nombre" => "CROACIA"],
            ["clave" => "50","nombre" => "CUBA"],
            ["clave" => "51","nombre" => "DINAMARCA"],
            ["clave" => "52","nombre" => "DJIBOUTI"],
            ["clave" => "53","nombre" => "DOMINICA"],
            ["clave" => "54","nombre" => "ECUADOR"],
            ["clave" => "55","nombre" => "EGIPTO"],
            ["clave" => "56","nombre" => "EL SALVADOR"],
            ["clave" => "57","nombre" => "EMIRATOS ARABES UNIDOS"],
            ["clave" => "58","nombre" => "ERITREA"],
            ["clave" => "59","nombre" => "ESLOVAQUIA"],
            ["clave" => "60","nombre" => "ESLOVENIA"],
            ["clave" => "61","nombre" => "ESPAÑA"],
            ["clave" => "62","nombre" => "ESTADOS UNIDOS DE AMERICA"],
            ["clave" => "63","nombre" => "ESTONIA"],
            ["clave" => "64","nombre" => "ETIOPIA"],
            ["clave" => "65","nombre" => "FEDERACION DE RUSIA"],
            ["clave" => "66","nombre" => "FIJI"],
            ["clave" => "67","nombre" => "FILIPINAS"],
            ["clave" => "68","nombre" => "FINLANDIA"],
            ["clave" => "69","nombre" => "FRANCIA"],
            ["clave" => "70","nombre" => "GABON"],
            ["clave" => "71","nombre" => "GAMBIA"],
            ["clave" => "72","nombre" => "GEORGIA"],
            ["clave" => "73","nombre" => "GHANA"],
            ["clave" => "74","nombre" => "GIBRALTAR"],
            ["clave" => "75","nombre" => "GRANADA"],
            ["clave" => "76","nombre" => "GRECIA"],
            ["clave" => "77","nombre" => "GROENLANDIA"],
            ["clave" => "78","nombre" => "GUADALUPE"],
            ["clave" => "79","nombre" => "GUAM"],
            ["clave" => "80","nombre" => "GUATEMALA"],
            ["clave" => "81","nombre" => "GUAYANA FRANCESA"],
            ["clave" => "82","nombre" => "GUINEA"],
            ["clave" => "83","nombre" => "GUINEA BISSAU"],
            ["clave" => "84","nombre" => "GUINEA ECUATORIAL"],
            ["clave" => "85","nombre" => "GUYANA"],
            ["clave" => "86","nombre" => "HAITI"],
            ["clave" => "87","nombre" => "HONDURAS"],
            ["clave" => "88","nombre" => "HONG KONG"],
            ["clave" => "89","nombre" => "HUNGRIA"],
            ["clave" => "90","nombre" => "INDIA"],
            ["clave" => "91","nombre" => "INDONESIA"],
            ["clave" => "92","nombre" => "IRAN"],
            ["clave" => "93","nombre" => "IRAQ"],
            ["clave" => "94","nombre" => "IRLANDA"],
            ["clave" => "95","nombre" => "ISLA BOUVET"],
            ["clave" => "96","nombre" => "ISLA DE CHRISTMAS"],
            ["clave" => "97","nombre" => "ISLA NORFOLK"],
            ["clave" => "98","nombre" => "ISLANDIA"],
            ["clave" => "99","nombre" => "ISLAS CAIMAN"],
            ["clave" => "100","nombre" => "ISLAS COOK"],
            ["clave" => "101","nombre" => "ISLAS DE COCOS (KEELING)"],
            ["clave" => "102","nombre" => "ISLAS FALKLAND (MALVINAS)"],
            ["clave" => "103","nombre" => "ISLAS FAROE"],
            ["clave" => "104","nombre" => "ISLAS GEORGIA DEL SUR Y SANDWICH DEL SUR"],
            ["clave" => "105","nombre" => "ISLAS HEARD Y MCDONALD"],
            ["clave" => "106","nombre" => "ISLAS MARIANAS DEL NORTE"],
            ["clave" => "107","nombre" => "ISLAS MARSHALL"],
            ["clave" => "108","nombre" => "ISLAS SALOMON"],
            ["clave" => "109","nombre" => "ISLAS TURCAS Y CAICOS"],
            ["clave" => "110","nombre" => "ISLAS VIRGENES BRITANICAS"],
            ["clave" => "111","nombre" => "ISLAS VIRGENES DE ESTADOS UNIDOS DE AMERICA"],
            ["clave" => "112","nombre" => "ISRAEL"],
            ["clave" => "113","nombre" => "ITALIA"],
            ["clave" => "114","nombre" => "JAMAICA"],
            ["clave" => "115","nombre" => "JAPON"],
            ["clave" => "116","nombre" => "JORDANIA"],
            ["clave" => "117","nombre" => "KAZAJSTAN"],
            ["clave" => "118","nombre" => "KENIA"],
            ["clave" => "119","nombre" => "KIRGUISTAN"],
            ["clave" => "120","nombre" => "KIRIBATI"],
            ["clave" => "121","nombre" => "KUWAIT"],
            ["clave" => "122","nombre" => "LESOTHO"],
            ["clave" => "123","nombre" => "LETONIA"],
            ["clave" => "124","nombre" => "LIBANO"],
            ["clave" => "125","nombre" => "LIBERIA"],
            ["clave" => "126","nombre" => "LIBIA"],
            ["clave" => "127","nombre" => "LIECHTENSTEIN"],
            ["clave" => "128","nombre" => "LITUANIA"],
            ["clave" => "129","nombre" => "LUXEMBURGO"],
            ["clave" => "130","nombre" => "MACAU"],
            ["clave" => "131","nombre" => "MACEDONIA"],
            ["clave" => "132","nombre" => "MADAGASCAR"],
            ["clave" => "133","nombre" => "MALASIA"],
            ["clave" => "134","nombre" => "MALAWI"],
            ["clave" => "135","nombre" => "MALDIVAS"],
            ["clave" => "136","nombre" => "MALI"],
            ["clave" => "137","nombre" => "MALTA"],
            ["clave" => "138","nombre" => "MARRUECOS"],
            ["clave" => "139","nombre" => "MARTINICA"],
            ["clave" => "140","nombre" => "MAURICIO"],
            ["clave" => "141","nombre" => "MAURITANIA"],
            ["clave" => "142","nombre" => "MAYOTTE"],
            ["clave" => "143","nombre" => "MEXICO"],
            ["clave" => "144","nombre" => "MICRONESIA"],
            ["clave" => "145","nombre" => "MONACO"],
            ["clave" => "146","nombre" => "MONGOLIA"],
            ["clave" => "147","nombre" => "MONTSERRAT"],
            ["clave" => "148","nombre" => "MOZAMBIQUE"],
            ["clave" => "149","nombre" => "MYANMAR"],
            ["clave" => "150","nombre" => "NAMIBIA"],
            ["clave" => "151","nombre" => "NAURU"],
            ["clave" => "152","nombre" => "NEPAL"],
            ["clave" => "153","nombre" => "NICARAGUA"],
            ["clave" => "154","nombre" => "NIGER"],
            ["clave" => "155","nombre" => "NIGERIA"],
            ["clave" => "156","nombre" => "NIUE"],
            ["clave" => "157","nombre" => "NORUEGA"],
            ["clave" => "158","nombre" => "NUEVA CALEDONIA"],
            ["clave" => "159","nombre" => "NUEVA ZELANDIA"],
            ["clave" => "160","nombre" => "OMAN"],
            ["clave" => "161","nombre" => "PAISES BAJOS"],
            ["clave" => "162","nombre" => "PAKISTAN"],
            ["clave" => "163","nombre" => "PALAU"],
            ["clave" => "164","nombre" => "PANAMA"],
            ["clave" => "165","nombre" => "PAPUA NUEVA GUINEA"],
            ["clave" => "166","nombre" => "PARAGUAY"],
            ["clave" => "167","nombre" => "PERU"],
            ["clave" => "168","nombre" => "PITCAIRN"],
            ["clave" => "169","nombre" => "POLINESIA FRANCESA"],
            ["clave" => "170","nombre" => "POLONIA"],
            ["clave" => "171","nombre" => "PORTUGAL"],
            ["clave" => "172","nombre" => "PUERTO RICO"],
            ["clave" => "173","nombre" => "QATAR"],
            ["clave" => "174","nombre" => "REINO UNIDO DE GRAN BRETAÑA E IRLANDA DEL NORTE"],
            ["clave" => "175","nombre" => "REPUBLICA ARABE SIRIA"],
            ["clave" => "176","nombre" => "REPUBLICA CENTROAFRICANA"],
            ["clave" => "177","nombre" => "REPUBLICA CHECA"],
            ["clave" => "178","nombre" => "REPUBLICA DE COREA"],
            ["clave" => "179","nombre" => "REPUBLICA DE MOLDOVA"],
            ["clave" => "180","nombre" => "REPUBLICA DEMOCRATICA DEL CONGO"],
            ["clave" => "181","nombre" => "REPUBLICA DEMOCRATICA POPULAR DE LAO"],
            ["clave" => "182","nombre" => "REPUBLICA DOMINICANA"],
            ["clave" => "183","nombre" => "REPUBLICA POPULAR DEMOCRATICA DE COREA"],
            ["clave" => "184","nombre" => "REPUBLICA UNIDA DE TANZANIA"],
            ["clave" => "185","nombre" => "REUNION"],
            ["clave" => "186","nombre" => "RUANDA"],
            ["clave" => "187","nombre" => "RUMANIA"],
            ["clave" => "188","nombre" => "SAHARA OCCIDENTAL"],
            ["clave" => "189","nombre" => "SAMOA"],
            ["clave" => "190","nombre" => "SAMOA AMERICANA"],
            ["clave" => "191","nombre" => "SAN CRISTOBAL Y NEVIS"],
            ["clave" => "192","nombre" => "SAN MARINO"],
            ["clave" => "193","nombre" => "SAN PIERRE Y MIQUELON"],
            ["clave" => "194","nombre" => "SAN VICENTE Y LAS GRANADINAS"],
            ["clave" => "195","nombre" => "SANTA HELENA"],
            ["clave" => "196","nombre" => "SANTA LUCIA"],
            ["clave" => "197","nombre" => "SANTA SEDE (ESTADO CIUDAD DEL VATICANO)"],
            ["clave" => "198","nombre" => "SANTO TOME Y PRINCIPE"],
            ["clave" => "199","nombre" => "SENEGAL"],
            ["clave" => "200","nombre" => "SEYCHELLES"],
            ["clave" => "201","nombre" => "SIERRA LEONA"],
            ["clave" => "202","nombre" => "SINGAPUR"],
            ["clave" => "203","nombre" => "SOMALIA"],
            ["clave" => "204","nombre" => "SRI LANKA"],
            ["clave" => "205","nombre" => "SUDAFRICA"],
            ["clave" => "206","nombre" => "SUDAN"],
            ["clave" => "207","nombre" => "SUECIA"],
            ["clave" => "208","nombre" => "SUIZA"],
            ["clave" => "209","nombre" => "SURINAME"],
            ["clave" => "210","nombre" => "SVALBARD Y JAN MAYEN"],
            ["clave" => "211","nombre" => "SWAZILANDIA"],
            ["clave" => "212","nombre" => "TAILANDIA"],
            ["clave" => "213","nombre" => "TAIWAN"],
            ["clave" => "214","nombre" => "TAYIKISTAN"],
            ["clave" => "215","nombre" => "TERRITORIO BRITANICO DEL OCEANO INDICO"],
            ["clave" => "216","nombre" => "TERRITORIOS FRANCESES DEL SUR"],
            ["clave" => "217","nombre" => "TIMOR DEL ESTE"],
            ["clave" => "218","nombre" => "TOGO"],
            ["clave" => "219","nombre" => "TOKELAU"],
            ["clave" => "220","nombre" => "TONGA"],
            ["clave" => "221","nombre" => "TRINIDAD Y TOBAGO"],
            ["clave" => "222","nombre" => "TUNEZ"],
            ["clave" => "223","nombre" => "TURKMENISTAN"],
            ["clave" => "224","nombre" => "TURQUIA"],
            ["clave" => "225","nombre" => "TUVALU"],
            ["clave" => "226","nombre" => "UCRANIA"],
            ["clave" => "227","nombre" => "UGANDA"],
            ["clave" => "228","nombre" => "URUGUAY"],
            ["clave" => "229","nombre" => "UZBEKISTAN"],
            ["clave" => "230","nombre" => "VANUATU"],
            ["clave" => "231","nombre" => "VENEZUELA"],
            ["clave" => "232","nombre" => "VIETNAM"],
            ["clave" => "233","nombre" => "WALLIS Y FUTUNA"],
            ["clave" => "234","nombre" => "YEMEN"],
            ["clave" => "235","nombre" => "YUGOSLAVIA"],
            ["clave" => "236","nombre" => "ZAMBIA"],
            ["clave" => "237","nombre" => "ZIMBABUE"],
            ["clave" => "238","nombre" => "SIN DATO"],
            ["clave" => "239","nombre" => "PAIS POR REVISAR"],
            ["clave" => "240","nombre" => "BONAIRE, SAN EUSTAQUIO, SABA"],
            ["clave" => "241","nombre" => "CURAZAO"],
            ["clave" => "242","nombre" => "ISLA DE SAINT MARTEEN"],
            ["clave" => "243","nombre" => "ISLA WAKE"],
            ["clave" => "244","nombre" => "ISLAS ANGLONORMANDAS"],
            ["clave" => "245","nombre" => "ISLAS DE MAN"],
            ["clave" => "246","nombre" => "MONTENEGRO"],
            ["clave" => "247","nombre" => "PALESTINA"],
            ["clave" => "248","nombre" => "SUDAN"],
            ["clave" => "249","nombre" => "SUDAN DEL SUR"],

        ];

        foreach($datos as $dato)
            Pais::create($dato);
    }
}
