<?php

namespace Database\Seeders;

use App\Models\ViolacionDH;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ViolacionDHSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $datos = [
            ["clave"=> "1","nombre" => "ABUSO DE AUTORIDAD"],
            ["clave"=> "2","nombre" => "ABUSO SEXUAL"],
            ["clave"=> "3","nombre" => "AMENAZAS"],
            ["clave"=> "4","nombre" => "CATEO ILEGAL"],
            ["clave"=> "5","nombre" => "DELINCUENCIA ORGANIZADA"],
            ["clave"=> "6","nombre" => "DELITOS COMETIDOS POR SERVIDORES PUBLICOS"],
            ["clave"=> "7","nombre" => "DELITOS CONTRA LA SALUD"],
            ["clave"=> "8","nombre" => "DERECHO A LA ALIMENTACION"],
            ["clave"=> "9","nombre" => "DERECHO A LA AUTONOMIA REPRODUCTIVA"],
            ["clave"=> "10","nombre" => "DERECHO A LA CIRCULACION"],
            ["clave"=> "11","nombre" => "DERECHO A LA DEBIDA PROCURACION DE JUSTICIA"],
            ["clave"=> "12","nombre" => "DERECHO A LA INFORMACION DE LA VERDAD"],
            ["clave"=> "13","nombre" => "DERECHO A LA INFORMACION EN MATERIA DE SALUD"],
            ["clave"=> "14","nombre" => "DERECHO A LA INTEGRIDAD"],
            ["clave"=> "15","nombre" => "DERECHO A LA INTEGRIDAD PERSONAL"],
            ["clave"=> "16","nombre" => "DERECHO A LA INTEGRIDAD SEXUAL"],
            ["clave"=> "17","nombre" => "DERECHO A LA LEGALIDAD"],
            ["clave"=> "18","nombre" => "DERECHO A LA LIBERTAD"],
            ["clave"=> "19","nombre" => "DERECHO A LA LIBERTAD DE REUNION"],
            ["clave"=> "20","nombre" => "DERECHO A LA LIBERTAD DE TRANSITO"],
            ["clave"=> "21","nombre" => "DERECHO A LA LIBERTAD PERSONAL"],
            ["clave"=> "22","nombre" => "DERECHO A LA PRESUNCION DE INOCENCIA"],
            ["clave"=> "23","nombre" => "DERECHO A LA PROCURACION DE JUSTICIA"],
            ["clave"=> "24","nombre" => "DERECHO A LA PROTECCION DE LA SALUD"],
            ["clave"=> "25","nombre" => "DERECHO A LA RESIDENCIA"],
            ["clave"=> "26","nombre" => "DERECHO A LA SALUD"],
            ["clave"=> "27","nombre" => "DERECHO A LA SEGURIDAD"],
            ["clave"=> "28","nombre" => "DERECHO A LA SEGURIDAD JURIDICA"],
            ["clave"=> "29","nombre" => "DERECHO A LA SEGURIDAD PERSONAL"],
            ["clave"=> "30","nombre" => "DERECHO A LA VERDAD"],
            ["clave"=> "31","nombre" => "DERECHO A LA VIDA"],
            ["clave"=> "32","nombre" => "DERECHO A LA VIVIENDA"],
            ["clave"=> "33","nombre" => "DERECHO A UNA DEFENSA ADECUADA"],
            ["clave"=> "34","nombre" => "DERECHO AL ACCESO A LA INFORMACION"],
            ["clave"=> "35","nombre" => "DERECHO AL ACCESO A LA JUSTICIA"],
            ["clave"=> "36","nombre" => "DERECHO AL DEBIDO PROCESO"],
            ["clave"=> "37","nombre" => "DERECHO AL TRATO DIGNO"],
            ["clave"=> "38","nombre" => "DERECHO DE ACCESO A LA JUSTICIA"],
            ["clave"=> "39","nombre" => "DERECHO DE LEGALIDAD"],
            ["clave"=> "40","nombre" => "DESAPARICION DE PERSONA"],
            ["clave"=> "41","nombre" => "DESAPARICION FORZADA"],
            ["clave"=> "42","nombre" => "DETENCION ARBITRARIA"],
            ["clave"=> "43","nombre" => "DILACION EN EL PROCEDIMIENTO ADMINISTRATIVO"],
            ["clave"=> "44","nombre" => "HOMICIDIO"],
            ["clave"=> "45","nombre" => "HOMICIDIO CALIFICADO"],
            ["clave"=> "46","nombre" => "HOMICIDIO CULPOSO"],
            ["clave"=> "47","nombre" => "HOMICIDIO EN GRADO DE RESPONSABILIDAD PROFESIONAL"],
            ["clave"=> "48","nombre" => "INADECUADA ATENCION MEDICA"],
            ["clave"=> "49","nombre" => "INTEGRIDAD PERSONAL"],
            ["clave"=> "50","nombre" => "INTIMIDACION"],
            ["clave"=> "51","nombre" => "LA AUTORIDAD NO SEÑALA DELITO Y/O VIOLACION A DDHH"],
            ["clave"=> "52","nombre" => "LESIONES"],
            ["clave"=> "53","nombre" => "LO QUE RESULTE"],
            ["clave"=> "54","nombre" => "NEGLIGENCIA MEDICA"],
            ["clave"=> "55","nombre" => "OMITIR RESPETAR LA GARANTIA DE AUDIENCIA"],
            ["clave"=> "56","nombre" => "OTROS"],
            ["clave"=> "57","nombre" => "PERDIDA DE LA VIDA"],
            ["clave"=> "58","nombre" => "PERSONA DESAPARECIDA"],
            ["clave"=> "59","nombre" => "PORTACION DE ARMA"],
            ["clave"=> "60","nombre" => "PRESTAR INDEBIDAMENTE EL SERVICIO PUBLICO"],
            ["clave"=> "61","nombre" => "PRIVACION ILEGAL"],
            ["clave"=> "62","nombre" => "PRIVACION ILEGAL DE LA LIBERTAD"],
            ["clave"=> "63","nombre" => "RESPONSABILIDAD PROFESIONAL"],
            ["clave"=> "64","nombre" => "RETENCION"],
            ["clave"=> "65","nombre" => "RETENCION ILEGAL"],
            ["clave"=> "66","nombre" => "ROBO"],
            ["clave"=> "67","nombre" => "SECUESTRO"],
            ["clave"=> "68","nombre" => "TORTURA"],
            ["clave"=> "69","nombre" => "TRATOS CRUDOS"],
            ["clave"=> "70","nombre" => "TRATOS CRUELES"],
            ["clave"=> "71","nombre" => "TRATOS DEGRADANTES"],
            ["clave"=> "72","nombre" => "TRATOS INHUMANOS"],
            ["clave"=> "73","nombre" => "USO EXCESIVO DE LA FUERZA"],
            ["clave"=> "74","nombre" => "VIDA LIBRE DE VIOLENCIA"],
            ["clave"=> "75","nombre" => "VIOLACION"],
            ["clave"=> "76","nombre" => "VIOLACION A LA LEGALIDAD"],
            ["clave"=> "77","nombre" => "VIOLACION A LA LIBERTAD"],
            ["clave"=> "78","nombre" => "VIOLACION A LA SEGURIDAD JURIDICA"],
            ["clave"=> "79","nombre" => "VIOLACION A LOS DERECHOS FUNDAMENTALES"],
            ["clave"=> "80","nombre" => "VIOLACION A SALUD"],
            ["clave"=> "81","nombre" => "VIOLACION AL DERECHO DE LA VIDA"],
            ["clave"=> "82","nombre" => "VIOLACION AL TRATO DIGNO"],
            ["clave"=> "83","nombre" => "VIOLACION EQUIPARADA"],
            ["clave"=> "84","nombre" => "VIOLENCIA OBSTETRICA"],
            ["clave"=> "85","nombre" => "SIN DATO"],
            ["clave"=> "86","nombre" => "PRIVACION DEL LIBRE DESARROLLO DEL MENOR"],
            ["clave"=> "87","nombre" => "DERECHO A LA INTEGRIDAD FISICA"],
            ["clave"=> "88","nombre" => "DERECHO A LA LIBERTAD DE EXPRESION"],
            ["clave"=> "89","nombre" => "A LA DEFENSA DE LOS DERECHOS HUMANOS"],
            ["clave"=> "90","nombre" => "DERECHO A LA CONSULTA, LIBRE, PREVIA E INFORMADA"],
            ["clave"=> "91","nombre" => "LA AUTORIDAD NO SEÑALA VIOLACION A DDHH"],
            ["clave"=> "92","nombre" => "A LA INTEGRIDAD FISICA Y PSICOLOGICA"],
            ["clave"=> "93","nombre" => "A LA DIGNIDAD"],
            ["clave"=> "94","nombre" => "DERECHO A LA IGUALDAD Y A LA EDUCACION"],
            ["clave"=> "95","nombre" => "DERECHO A LA PROPIEDAD"],
            ["clave"=> "96","nombre" => "DERECHO AL TRABAJO"],
            ["clave"=> "97","nombre" => "DERECHO AL AGUA"],
            ["clave"=> "98","nombre" => "VIDA LIBRE DE VIOLENCIA OBSTETRICA"],
            ["clave"=> "99","nombre" => "DERECHO DE INTIMIDAD"],
            ["clave"=> "100","nombre" => "SEGURIDAD JURIDICA POR LA EXHIBICION INDEBIDA DE F"],
            ["clave"=> "101","nombre" => "DERECHO A LA EDUCACION"],
            ["clave"=> "102","nombre" => "PRINCIPIO DEL INTERES SUPERIOR DE LA NIÑEZ"],
            ["clave"=> "103","nombre" => "VIOLENCIA SEXUAL"],
            ["clave"=> "104","nombre" => "INVIOLABILIDAD DEL DOMICILIO"],
            ["clave"=> "105","nombre" => "DERECHO A LA PERSONALIDAD JURIDICA"],
            ["clave"=> "106","nombre" => "GARANTIAS JUDICIALES Y A LA PROTECCION JUDICIAL"],
            ["clave"=> "107","nombre" => "INTEGRIDAD PSIQUICA Y MORAL"],
            ["clave"=> "108","nombre" => "VIDA PRIVADA FAMILIAR"],
            ["clave"=> "109","nombre" => "LIBERTAD DE CIRCULACION Y RESIDENCIA"],
            ["clave"=> "110","nombre" => "DEBER DE ESPECIAL PROTECCION DE NIÑOS Y NIÑAS"],
            ["clave"=> "111","nombre" => "DERECHO A LA IGUALDAD Y LA NO DISCRIMINACION"],
            ["clave"=> "112","nombre" => "DERECHO A LA SEGURIDAD SOCIAL"],
            ["clave"=> "113","nombre" => "VIOLACION AGRAVADA EN GRADO DE TENTATIVA"],
            ["clave"=> "114","nombre" => "DERECHO A LA REINSERCION SOCIAL"],
            ["clave"=> "115","nombre" => "DERECHO DE PROTECCION A LA FAMILIA"],
            ["clave"=> "116","nombre" => "DERECHO A LA IDENTIDAD CULTURAL"],
            ["clave"=> "117","nombre" => "VIOLACION A LA INTEGRIDAD PSICOLOGICA"],
            ["clave"=> "118","nombre" => "DERECHO AL INTERES SUPERIOR DE LA NIÑEZ"],
            ["clave"=> "119","nombre" => "DERECHO A LA NO DISCRIMINACION"],
            ["clave"=> "120","nombre" => "A LA DEBIDA PROCURACION DE JUSTICIA DERECHO A LA INTEGRIDAD"],
            ["clave"=> "121","nombre" => "A LA SALUD"],
            ["clave"=> "122","nombre" => "A LA VIDA"],
            ["clave"=> "123","nombre" => "ACTOS VIOLATORIOS DE DERECHOS HUMANOS POR LA POLICIA ESTATAL"],
            ["clave"=> "124","nombre" => "AGRESIONES SEXUALES"],
            ["clave"=> "125","nombre" => "AGRUPACION DELICTUOSA"],
            ["clave"=> "126","nombre" => "AL INTERES SUPERIOR DEL NIÑO Y LA NIÑA EN AGRAVIO DE KARLA YODALI RUIZ ARREOLA DIEGO ALEJANDRO CALDERON RUIZ Y KEVIN ALEXANDER CALDERON RUIZ Y VULNERACION DEL DERECHO A LA VIDA DE DIEGO ALEJANDRO CAL"],
            ["clave"=> "127","nombre" => "ATENTADOS CONTRA LA VIDA"],
            ["clave"=> "128","nombre" => "CRIMEN DE LESA HUMANIDAD"],
            ["clave"=> "129","nombre" => "DAÑO EN PROPIEDAD AJENA"],
            ["clave"=> "130","nombre" => "DDHH DE LAS MUJERES"],
            ["clave"=> "131","nombre" => "DEBIDO ILEGAL DE LA LIBERTAD"],
            ["clave"=> "132","nombre" => "DERECHO A LA DEBIDA PROCURACION DE JUSTICIA Y DE LAS VICTIMAS DE DELITO"],
            ["clave"=> "133","nombre" => "DERECHO A LA IGUALDAD"],
            ["clave"=> "134","nombre" => "DERECHO A LA JUSTICIA"],
            ["clave"=> "135","nombre" => "DERECHO A LA SALUD DE UN MENOR Y A LA VIDA"],
            ["clave"=> "136","nombre" => "DERECHO A LA SEGURIDAD PERSONALE"],
            ["clave"=> "137","nombre" => "DERECHO AL ACCESO A LA IMPARTICION DE JUSTICIA Y ACCESO A LOS DERECHOS QUE LE CORRESPONDEN A LAS VICTIMAS Y OFENDIDOS DEL DELITO"],
            ["clave"=> "138","nombre" => "DERECHO AL ACCESO DE LA JUSTICIA"],
            ["clave"=> "139","nombre" => "DERECHO DE FAMILIA"],
            ["clave"=> "140","nombre" => "DERECHO SEXUAL"],
            ["clave"=> "141","nombre" => "DERECHOS SEXUALES Y REPRODUCTIVOS"],
            ["clave"=> "142","nombre" => "DESAPARICION"],
            ["clave"=> "143","nombre" => "DESAPARICION EXTRAJUDICIAL"],
            ["clave"=> "144","nombre" => "DESAPARICION FORZADA DE PERSONAS"],
            ["clave"=> "145","nombre" => "DESPLAZAMIENTO FORZADO Y DERECHOS QUE SE VIOLAN A SU CONSECUENCIA"],
            ["clave"=> "146","nombre" => "DETENCION ILEGAL"],
            ["clave"=> "147","nombre" => "DILACION EN SU PROCESO"],
            ["clave"=> "148","nombre" => "DIVERSAS"],
            ["clave"=> "149","nombre" => "DIVERSAS VIOLACIONES"],
            ["clave"=> "150","nombre" => "EJECUCION EXTRAJUDICIAL"],
            ["clave"=> "151","nombre" => "EJERCICIO INDEBIDO DEL SERVICIO PUBLICO"],
            ["clave"=> "152","nombre" => "EL MP NO INVESTIGABA"],
            ["clave"=> "153","nombre" => "ENTRE OTROS DERECHOS DE LA SALUD"],
            ["clave"=> "154","nombre" => "FALTA DE INVESTIGACION Y PROPORCION DE RESULTADOS"],
            ["clave"=> "155","nombre" => "HOMICIDIO CULPOSO CON LA CALIFICATIVA DE RESPONSABILIDAD PROFESIONAL"],
            ["clave"=> "156","nombre" => "INADECUADA ATENCION MEDICA EN DIVERSOS HOSPITALES DEL IMSS"],
            ["clave"=> "157","nombre" => "INADECUADA ATENCION MEDICA Y PERDIDA DE LA VIDA"],
            ["clave"=> "158","nombre" => "INDEBIDA PROCURACION DE JUSTICIA"],
            ["clave"=> "159","nombre" => "INDEBIDA PROCURACION DE JUSTICIA Y OBSTACULIZACION DE LA ADMINISTRACION DE DEL LUGAR DE RESIDENCIA Y TRANSITO DENTRO DEL PAIS"],
            ["clave"=> "160","nombre" => "INHUMANOS O DEGRADANTES"],
            ["clave"=> "161","nombre" => "JUSTICIA"],
            ["clave"=> "162","nombre" => "LA AUTORIDAD NO SEÑA LA DELITO Y/O VIOLACION A DDHH"],
            ["clave"=> "163","nombre" => "LA AUTORIDAD NO SEÑA LA VIOLACION A DDHH"],
            ["clave"=> "164","nombre" => "LEGALIDAD"],
            ["clave"=> "165","nombre" => "LESIONES COMETIDOS POR SERVIDORES PUBLICOS FEDERALES"],
            ["clave"=> "166","nombre" => "LESIONES EN GRADO DE RESPONSABILIDAD PROFESIONAL"],
            ["clave"=> "167","nombre" => "LESIONES QUE GENERARON INCAPACIDAD PERMANENTE"],
            ["clave"=> "168","nombre" => "LIBERTAD"],
            ["clave"=> "169","nombre" => "LIBERTAD SEXUAL"],
            ["clave"=> "170","nombre" => "LOS HECHOS VIOLATORIOS REGISTRADOS EN LA QUEJA FUERON: OMITIR RESPETAR LA GARANTIA DE AUDIENCIA. PRESTAR INDEBIDAMENTE EL SERVICIO PUBLICO Y DILACION EN EL PROCEDIMIENTO ADMINISTRATIVO"],
            ["clave"=> "171","nombre" => "MALA PRAXIS"],
            ["clave"=> "172","nombre" => "MEDIDAS CAUTELARES Y VIOLENCIA FAMILIAR"],
            ["clave"=> "173","nombre" => "NEGACION A INICIAR AP"],
            ["clave"=> "174","nombre" => "NO DISCRIMINACION"],
            ["clave"=> "175","nombre" => "NO INTEGRACION DE LA INVESTIGACION EN SU MOMENTO"],
            ["clave"=> "176","nombre" => "OBSTACULIZACION DE LA ADMINISTRACION DE JUSTICIA"],
            ["clave"=> "177","nombre" => "OBSTRUCCION DE ACCESO A LA JUSTICIA"],
            ["clave"=> "178","nombre" => "OMISION DE CUMPLIMIENTO DE LAS NORMAS DEL MEDIO AMBIENTE"],
            ["clave"=> "179","nombre" => "OMISION DE ESTABLECER MEDIDAS CAUTELARES"],
            ["clave"=> "180","nombre" => "OMISIONES DE SERVIDORES PUBLICOS"],
            ["clave"=> "181","nombre" => "OMISIONES Y RETRASO EN LA INTEGRACION DE LA AP"],
            ["clave"=> "182","nombre" => "POSIBLE PRIVACION ILEGAL DE LA LIBERTAD"],
            ["clave"=> "183","nombre" => "PRIVACION DE LA LIBERTAD"],
            ["clave"=> "184","nombre" => "PRIVACION DE LA VIDA"],
            ["clave"=> "185","nombre" => "PRIVACION DE LA VIDA Y ATENTADOS CONTRA LA VIDA"],
            ["clave"=> "186","nombre" => "QUINTA VISITADURIA GENERAL"],
            ["clave"=> "187","nombre" => "RATIFICACION CONTRA PGR PGJECH Y QUIEN RESULTE RESPONSABLE DE DICHAS VIOLACIONES"],
            ["clave"=> "188","nombre" => "RATIFICACION CONTRA POR DIVERSA VIOLACION"],
            ["clave"=> "189","nombre" => "RATIFICACION CONTRA POR DIVERSAS VIOLACIONES"],
            ["clave"=> "190","nombre" => "RECOMENDACION"],
            ["clave"=> "191","nombre" => "RESTRICCION DEL LUGAR DE RESIDENCIA Y TRANSITO DENTRO DEL PAIS"],
            ["clave"=> "192","nombre" => "ROBO A BIENES PATRIMONIALES"],
            ["clave"=> "193","nombre" => "SALUD"],
            ["clave"=> "194","nombre" => "SE MANDO LA DOCUMENTACION PERO SIN FIRMAR"],
            ["clave"=> "195","nombre" => "SE VIOLAN POR PARTE DE LA CNDH LOS DERECHOS HUMANOS DE UNA FAMILIA AUTISTA"],
            ["clave"=> "196","nombre" => "SECUESTRO AGRAVADO"],
            ["clave"=> "197","nombre" => "SEGURIDAD"],
            ["clave"=> "198","nombre" => "SEGURIDAD PERSONAL"],
            ["clave"=> "199","nombre" => "SI"],
            ["clave"=> "200","nombre" => "SUBPROCURADURIA ESPECIALIZADA EN DELITOS FEDERALES"],
            ["clave"=> "201","nombre" => "TENTATIVA DE HOMICIDIO"],
            ["clave"=> "202","nombre" => "TRANSGRESION A LOS DERECHOS A LA INTEGRIDAD"],
            ["clave"=> "203","nombre" => "TRATO DIGNO"],
            ["clave"=> "204","nombre" => "VIDA"],
            ["clave"=> "205","nombre" => "VIOLACION A LA LEY FEDERAL DE ARMAS DE FUEGO Y EXPLOSIVOS"],
            ["clave"=> "206","nombre" => "VIOLACION A LOS DERECHOS DEL NIÑO"],
            ["clave"=> "207","nombre" => "VIOLACION A LOS DERECHOS HUMANOS"],
            ["clave"=> "208","nombre" => "VIOLACION AL DERECHO A LA PROTECCION DE LA SALUD"],
            ["clave"=> "209","nombre" => "VIOLACION DE DERECHOS HUMANOS POR LA POLICIA ESTATAL"],
            ["clave"=> "210","nombre" => "VIOLACION SEXUAL"],
            ["clave"=> "211","nombre" => "VIOLACIONES AL PROCEDIMIENTO"],
            ["clave"=> "212","nombre" => "VIOLENCIA OBSTETRICA E INADECUADA ATENCION MEDICA Y PERDIDA DE PRODUCTO"],
            ["clave"=> "213","nombre" => "VULNERACION A LOS DERECHOS DE LA SEGURIDAD JURIDICA Y A LA PROCURACION DE JUSTICIA"],
            ["clave"=> "214","nombre" => "DERECHO A LA PRIVACIDAD"],
            ["clave"=> "215","nombre" => "DERECHO A LA SEGURIDAD PUBLICA"],
            ["clave"=> "216","nombre" => "DERECHO A LA LIBERTAD SEXUAL"],
            ["clave"=> "217","nombre" => "DERECHO AL DESARROLLO"],
            ["clave"=> "218","nombre" => "A LA PROTECCION DE LA MATERNIDAD EN EL TRABAJO"],
            ["clave"=> "219","nombre" => "AL DESARROLLO OPTIMO DEL PRODUCTO DE LA GESTACION"],
            ["clave"=> "220","nombre" => "ACCESO A LA INFORMACION EN MATERIA DE SALUD"],
            ["clave"=> "221","nombre" => "LACTANCIA MATERNA"],
            ["clave"=> "222","nombre" => "SANO DESARROLLO"],
            ["clave"=> "223","nombre" => "DERECHO A UNA ADECUADA ATENCION MEDICA"],
            ["clave"=> "224","nombre" => "DERECHO A LA IDENTIDAD"],
            ["clave"=> "225","nombre" => "DERECHO A LA FAMILIA"],
            ["clave"=> "226","nombre" => "DERECHO A DESARROLLO INTEGRAL"],
            ["clave"=> "227","nombre" => "DERECHO A LA LIBERTAD Y AUTONOMIA REPRODUCTIVA"],
            ["clave"=> "228","nombre" => "DERECHO A LA INFORMACION VERAZ Y OPORTUNA"],
            ["clave"=> "229","nombre" => "SANO DESARROLLO INTEGRAL"],
            ["clave"=> "230","nombre" => "DERECHO DE LOS PUEBLOS Y COMUNIDADES INDIGENAS"],
            ["clave"=> "231","nombre" => "DERECHO A UN NIVEL DE VIDA ADECUADO"],
            ["clave"=> "232","nombre" => "DERECHO AL DISFRUTE DEL NIVEL MAS ALTO POSIBLE DE SALUD"],
            ["clave"=> "233","nombre" => "DISCRIMINACION"],
            ["clave"=> "234","nombre" => "EJECUCION ARBITRARIA"],
            ["clave"=> "235","nombre" => "VIOLACIONES DE LESA HUMANIDAD"],
            ["clave"=> "236","nombre" => "DERECHO DE PETICION"],

        ];

        foreach($datos as $dato)
            ViolacionDH::create($dato);
    }
}
